name: CI

on:
  push:
    branches: [ "main", "*solution" ]
  pull_request:
    branches: [ "main", "*solution" ]

jobs:
  # This job will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
  # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
  build-ui:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./ui/package-lock.json
    - run: npm ci
    - run: npm run build:prod    
    - run: npm run lint
    - run: npm run test -- --watch=false

  build-api:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
