name: CI

on:
  push:
    branches: [ "main", "*solution" ]
  pull_request:
    branches: [ "main", "*solution" ]

jobs:
  # This job will do a clean installation of node dependencies, cache/restore them, build the source code and run tests
  # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
  build-ui:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui  

    steps:
    - uses: actions/checkout@v6
    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'
        cache-dependency-path: ./ui/package-lock.json
    - run: npm ci
    - run: npm run build    
    - run: npm run lint
    - run: npm run test:ci
    - name: 'Report Coverage'
      # Set if: always() to also generate the report if tests are failing
      # Only works if you set `reportOnFailure: true` in your vite config as specified above
      # if: always() 
      uses:  davelosert/vitest-coverage-report-action@v2
      with:
        working-directory: "./ui"
        json-summary-path: "./coverage/ng-in-action/coverage-summary.json"
        json-final-path: "./coverage/ng-in-action/coverage-final.json"
        threshold-icons: "{0: '🔴', 80: '🟠', 90: '🟢'}"

  # This job will do a clean installation of NuGet dependencies, restore them, build the source code and run tests
  # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
  build-api:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
